# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d525deff98c90bf43539a5979d445cb815d8c65f802caf2bc21e20129aacc5b94853fc11db7d7951f9df3d53153f5071ff0254179d30a3010bf32430a95258

test:
  secret_key_base: e6197cd19e278a558d5847189f0e6a92b49040b8787d1e1eed5f43ddad4d8583bdac91e1cd75e20e390c701cf9c245c3d2a94aa206c68b3d7e9979aa9aef8463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
